### ISSUE TITLE
"Please install libtool" happens when run ./autogen.sh

### ISSUE THREAD

**Issue by leemgs** [kirushyk/gst-instruments#39] opened 2018-11-21 02:35 UTC
"Please install libtool" happens when run ./autogen.sh
### Distro
```bash

invain@mymate:/work/taos/gst-instruments$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
invain@mymate:/work/taos/gst-instruments$ uname -a
Linux mymate 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

## How to reproduce
```bash
s$ ./autogen.sh
Checking for autoreconf...
/usr/bin/autoreconf
Checking for pkg-config...
/usr/bin/pkg-config
Checking for aclocal...
/usr/bin/aclocal
Checking for libtool...
Please install libtool.

```

**Comment by ribalda** [comment] 2018-11-21 08:03
Hi @leemgs, have you tried installing libtool-bin ?

**Comment by ribalda** [comment] 2019-01-09 15:40
The issue is that OSX does not ship libtoolize, only libtool. We can do something like: https://github.com/zeromq/libzmq/pull/1497/commits/89fa904b2d753c981710fe6883ecc36ea879cedc But since there is a workaround (install libtool-bin) and we are moving to mesonbuild soon maybe it is not worth fixing this...

**Comment by kirushyk** [comment] 2020-07-06 13:21
Use Meson build

**Closed by kirushyk** 2020-07-06 13:21 UTC
Labels: wontfix
